### Example script - shows how to use this API client to access all variables' data for a single region at a specified resolution, in a specified country.

#### Load required libraries

In [1]:
from zoomin_client import client

#### Get metadata

In [2]:
# list of regions
region_list = client.get_region_metadata(version="v6",
                                        country_code = "at",
                                        spatial_resolution="NUTS3",
                                )

http://data.localised-project.eu/dsp/v6/at/region_metadata/?resolution=NUTS3

In [3]:
region_list

[{'resolution': 'NUTS3',
  'region_code': 'AT313',
  'region_name': 'Mühlviertel',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT321',
  'region_name': 'Lungau',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT224',
  'region_name': 'Oststeiermark',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT225',
  'region_name': 'West- und Südsteiermark',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT322',
  'region_name': 'Pinzgau-Pongau',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT323',
  'region_name': 'Salzburg und Umgebung',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT314',
  'region_name': 'Steyr-Kirchdorf',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT315',
  'region_name': 'Traunviertel',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT331',
  'region_name': 'Außerfern',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT332',
  'region_name': 'Innsbruck',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT333',
  'region_name': 'Osttirol',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT334',
  'region_name': 'Tiroler Oberland',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT223',
  'region_name': 'Östliche Obersteiermark',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT123',
  'region_name': 'Sankt Pölten',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT226',
  'region_name': 'Westliche Obersteiermark',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT311',
  'region_name': 'Innviertel',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT121',
  'region_name': 'Mostviertel-Eisenwurzen',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT122',
  'region_name': 'Niederösterreich-Süd',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT124',
  'region_name': 'Waldviertel',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT312',
  'region_name': 'Linz-Wels',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT335',
  'region_name': 'Tiroler Unterland',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT341',
  'region_name': 'Bludenz-Bregenzer Wald',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT342',
  'region_name': 'Rheintal-Bodenseegebiet',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT111',
  'region_name': 'Mittelburgenland',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT112',
  'region_name': 'Nordburgenland',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT113',
  'region_name': 'Südburgenland',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT127',
  'region_name': 'Wiener Umland/Südteil',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT213',
  'region_name': 'Unterkärnten',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT221',
  'region_name': 'Graz',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT222',
  'region_name': 'Liezen',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT130',
  'region_name': 'Wien',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT212',
  'region_name': 'Oberkärnten',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT126',
  'region_name': 'Wiener Umland/Nordteil',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT125',
  'region_name': 'Weinviertel',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'},
 {'resolution': 'NUTS3',
  'region_code': 'AT211',
  'region_name': 'Klagenfurt-Villach',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'}]

In [4]:
# single region
single_region = client.get_region_metadata(
                                version="v6",
                                country_code = "at",
                                spatial_resolution="NUTS3",
                                region_code = "AT111"
                                )

http://data.localised-project.eu/dsp/v6/at/region_metadata/?resolution=NUTS3

In [5]:
single_region

[{'resolution': 'NUTS3',
  'region_code': 'AT111',
  'region_name': 'Mittelburgenland',
  'year': 2021,
  'var_source_name': 'GISCO - Eurostat',
  'var_source_link': 'https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics',
  'var_source_citation': 'GISCO - Eurostat, ‘NUTS - GISCO - Eurostat’, 2021. https://ec.europa.eu/eurostat/web/gisco/geodata/statistical-units/territorial-units-statistics (accessed Nov. 23, 2022).',
  'var_source_license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)'}]

#### Get data - no filters

In [6]:
# All data
region_data = client.get_region_data(version = "v6", 
                                     country_code = "DE",
                                region_code = "DEA12",
                                mini_version=False,
                                result_format = "df"
                                )
#NOTE: Set mini_version to False to get all fields

http://data.localised-project.eu/dsp/v6/de/region_data/?region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=2&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=3&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=4&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=5&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=6&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=7&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=8&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=9&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=10&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=11&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=12&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=13&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=14&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=15&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=16&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=17&region=DEA12
http://data.localised-project.eu/dsp/v6/de/region_data/?page=18&region=DEA12

INFO:utils:Elapsed time for <function get_region_data at 0x000002958E211260>: 1.83 minutes

In [7]:
region_data

,value,year,pathway,climate_experiment,var_name,var_description,var_unit,data_last_update,var_aggregation_method,taggings,post_disagg_calculation_eq,var_source_name,var_source_link,var_source_citation,var_source_license,original_resolution,value_confidence_level
0,14.747883,2020.0,None,RCP2.6,cproj_annual_mean_maximum_temperature,Daily maximum temperature averaged over a year,degree celsius,2021,AVG,"[{'tag_dimension': 'sector', 'tag_name': 'weat...",None,EURO-CORDEX: new high-resolution climate chang...,https://www.euro-cordex.net/060378/index.php.en,"D. Jacob et al., ‘EURO-CORDEX: new high-resolu...",None,NUTS3,VERY HIGH
1,15.395976,2020.0,None,RCP4.5,cproj_annual_mean_maximum_temperature,Daily maximum temperature averaged over a year,degree celsius,2021,AVG,"[{'tag_dimension': 'sector', 'tag_name': 'weat...",None,EURO-CORDEX: new high-resolution climate chang...,https://www.euro-cordex.net/060378/index.php.en,"D. Jacob et al., ‘EURO-CORDEX: new high-resolu...",None,NUTS3,VERY HIGH
2,14.925311,2020.0,None,RCP8.5,cproj_annual_mean_maximum_temperature,Daily maximum temperature averaged over a year,degree celsius,2021,AVG,"[{'tag_dimension': 'sector', 'tag_name': 'weat...",None,EURO-CORDEX: new high-resolution climate chang...,https://www.euro-cordex.net/060378/index.php.en,"D. Jacob et al., ‘EURO-CORDEX: new high-resolu...",None,NUTS3,VERY HIGH
3,14.791762,2025.0,None,RCP2.6,cproj_annual_mean_maximum_temperature,Daily maximum temperature averaged over a year,degree celsius,2021,AVG,"[{'tag_dimension': 'sector', 'tag_name': 'weat...",None,EURO-CORDEX: new high-resolution climate chang...,https://www.euro-cordex.net/060378/index.php.en,"D. Jacob et al., ‘EURO-CORDEX: new high-resolu...",None,NUTS3,VERY HIGH
4,15.101608,2025.0,None,RCP4.5,cproj_annual_mean_maximum_temperature,Daily maximum temperature averaged over a year,degree celsius,2021,AVG,"[{'tag_dimension': 'sector', 'tag_name': 'weat...",None,EURO-CORDEX: new high-resolution climate chang...,https://www.euro-cordex.net/060378/index.php.en,"D. Jacob et al., ‘EURO-CORDEX: new high-resolu...",None,NUTS3,VERY HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,0.000000,2040.0,with_behavioural_changes,None,eucalc_tra_vehicle_fleet_freight_hdvl_phev_gas...,None,Mt/vehicle,2022,None,"[{'tag_dimension': 'sector', 'tag_name': 'tran...",eucalc_tra_emissions_co2e_freight_hdv/(eucalc_...,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0,MEDIUM
141,0.000000,2045.0,national,None,eucalc_tra_vehicle_fleet_freight_hdvl_phev_gas...,None,Mt/vehicle,2022,None,"[{'tag_dimension': 'sector', 'tag_name': 'tran...",eucalc_tra_emissions_co2e_freight_hdv/(eucalc_...,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0,MEDIUM
142,0.000000,2045.0,with_behavioural_changes,None,eucalc_tra_vehicle_fleet_freight_hdvl_phev_gas...,None,Mt/vehicle,2022,None,"[{'tag_dimension': 'sector', 'tag_name': 'tran...",eucalc_tra_emissions_co2e_freight_hdv/(eucalc_...,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0,MEDIUM
143,0.000000,2050.0,national,None,eucalc_tra_vehicle_fleet_freight_hdvl_phev_gas...,None,Mt/vehicle,2022,None,"[{'tag_dimension': 'sector', 'tag_name': 'tran...",eucalc_tra_emissions_co2e_freight_hdv/(eucalc_...,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0,MEDIUM
144,0.000000,2050.0,with_behavioural_changes,None,eucalc_tra_vehicle_fleet_freight_hdvl_phev_gas...,None,Mt/vehicle,2022,None,"[{'tag_dimension': 'sector', 'tag_name': 'tran...",eucalc_tra_emissions_co2e_freight_hdv/(eucalc_...,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0,MEDIUM

#### Get data - filter on variable

In [8]:
region_data_single_var = client.get_region_data(version="v6", 
                                                country_code = "de",
                                                region_code = "DE21",
                                                variable= "eucalc_tra_energy_demand_passenger_aviation",
                                                )

http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?region=DE21&variable=eucalc_tra_energy_demand_passenger_aviation

INFO:utils:Elapsed time for <function get_region_data at 0x000002958E211260>: 0.3 minutes

In [9]:
region_data_single_var

[{'value': 8.197759805038613,
  'year': 2020,
  'pathway': 'national',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 8.186989840631593,
  'year': 2020,
  'pathway': 'with_behavioural_changes',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 8.202789832867929,
  'year': 2025,
  'pathway': 'national',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.839906773836425,
  'year': 2025,
  'pathway': 'with_behavioural_changes',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 8.154255646737749,
  'year': 2030,
  'pathway': 'national',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.461297545769189,
  'year': 2030,
  'pathway': 'with_behavioural_changes',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.9621848554497925,
  'year': 2035,
  'pathway': 'national',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.000832641225596,
  'year': 2035,
  'pathway': 'with_behavioural_changes',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.761706076712774,
  'year': 2040,
  'pathway': 'national',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 6.552118964918843,
  'year': 2040,
  'pathway': 'with_behavioural_changes',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.589704597608993,
  'year': 2045,
  'pathway': 'national',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 6.134731359773607,
  'year': 2045,
  'pathway': 'with_behavioural_changes',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.436353892307469,
  'year': 2050,
  'pathway': 'national',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 5.740492079015982,
  'year': 2050,
  'pathway': 'with_behavioural_changes',
  'climate_experiment': None,
  'var_name': 'eucalc_tra_energy_demand_passenger_aviation',
  'var_unit': 'TWh',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'transport'},
   {'tag_dimension': 'type', 'tag_name': 'demand'},
   {'tag_dimension': 'commodity', 'tag_name': 'energy'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]}]

#### Get data - filter on pathway

NOTE: provides all data. Only the EUCalc data is filtered on the given pathway

In [10]:
region_data_single_pathway = client.get_region_data(version="v6", 
                                                    country_code = "de",
                                                region_code = "DE711",
                                                pathway_description = "with_behavioural_changes"
                                                )

http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?region=DE711&pathway=with_behavioural_changes
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=2&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=3&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=4&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=5&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=6&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=7&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=8&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=9&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=10&pathway=with_behavioural_changes&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?page=11&pathway=with_behavioural_changes&region=DE711

INFO:utils:Elapsed time for <function get_region_data at 0x000002958E211260>: 1.04 minutes

In [11]:
region_data_single_pathway

[{'value': 15.4200229644775,
  'year': 2020,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.0048637390137,
  'year': 2020,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.7220029830933,
  'year': 2020,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.3168172836304,
  'year': 2025,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.5827617645264,
  'year': 2025,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.3544044494629,
  'year': 2025,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'coldwave'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'coldwave'}]},
 {'value': -5.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'coldwave'}]},
 {'value': 15.4892272949219,
  'year': 2030,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.7135963439941,
  'year': 2030,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.3607587814331,
  'year': 2030,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': -5.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.0083446502686,
  'year': 2035,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.4923276901245,
  'year': 2035,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.6734886169434,
  'year': 2035,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.501407623291,
  'year': 2040,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.4417457580566,
  'year': 2040,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.2800769805908,
  'year': 2040,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.9351186752319,
  'year': 2045,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.5382499694824,
  'year': 2045,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.3076391220093,
  'year': 2045,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.9651107788086,
  'year': 2050,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.0659484863281,
  'year': 2050,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.2891292572021,
  'year': 2050,
  'pathway': None,
  'climate_experiment': 'RCP8.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP2.6',
  'var_name': 'cimp_change_in_frequency_of_heatwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_heatwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 1.0,
  'year': None,
  'pathway': None,

#### Get data - filter on climate experiment

NOTE: provides all data. Only the climate data is filtered on the given climate_experiment

In [12]:
region_data_single_clm_expt = client.get_region_data(version="v6", 
                                                country_code = "de",
                                                region_code = "DE711",
                                                pathway_description = "national",
                                                climate_experiment = "RCP4.5"
                                                )

http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?region=DE711&pathway=national&climate_experiment=RCP4.5
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=2&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=3&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=4&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=5&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=6&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=7&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=8&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=9&pathway=national&region=DE711
http://data.localised-project.eu/dsp/v6/de/region_data/mini_version/?climate_experiment=RCP4.5&page=10&pathway=national&region=DE711

INFO:utils:Elapsed time for <function get_region_data at 0x000002958E211260>: 0.68 minutes

In [13]:
region_data_single_clm_expt

[{'value': 16.0048637390137,
  'year': 2020,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.5827617645264,
  'year': 2025,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'coldwave'}]},
 {'value': 15.7135963439941,
  'year': 2030,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_coldwaves_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 15.4923276901245,
  'year': 2035,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.4417457580566,
  'year': 2040,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_extreme_drought_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.5382499694824,
  'year': 2045,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.0659484863281,
  'year': 2050,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_heatwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.692310333252,
  'year': 2075,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_heatwaves_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_heavy_precipitation_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 16.7794342041016,
  'year': 2099,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_maximum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_heavy_precipitation_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 11.7083950042725,
  'year': 2020,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_high_fire_risk_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 11.4788341522217,
  'year': 2025,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_high_fire_risk_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 11.3603000640869,
  'year': 2030,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_moderate_fire_risk_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 11.3175430297852,
  'year': 2035,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_moderate_fire_risk_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 11.9305782318115,
  'year': 2040,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 11.9608316421509,
  'year': 2045,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 11.7381477355957,
  'year': 2050,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_very_high_fire_risk_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_frequency_of_very_high_fire_risk_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'frequency'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 12.2666816711426,
  'year': 2075,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_intensity_of_coldwaves_maximum',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 12.4149894714356,
  'year': 2099,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_mean_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cimp_change_in_intensity_of_coldwaves_mean',
  'var_unit': '(categorical)',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'climate hazard'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 7.64313316345215,
  'year': 2020,
  'pathway': None,
  'climate_experiment': 'RCP4.5',
  'var_name': 'cproj_annual_mean_minimum_temperature',
  'var_unit': 'degree celsius',
  'taggings': [{'tag_dimension': 'sector', 'tag_name': 'weather and climate'},
   {'tag_dimension': 'type', 'tag_name': 'not applicable'},
   {'tag_dimension': 'commodity', 'tag_name': 'not applicable'},
   {'tag_dimension': 'resource', 'tag_name': 'not applicable'},
   {'tag_dimension': 'link', 'tag_name': 'not applicable'},
   {'tag_dimension': 'other', 'tag_name': 'not applicable'}]},
 {'value': 0.0,
  'year': None,
  'pathway': None,

#### Get data - filter on climate experiment and pathway

NOTE: provides all data. Only the climate data is filtered on the given climate_experiment and EUCalc data on the given pathway

In [14]:
region_data_minimal_set = client.get_region_data(version="v6", 
                                                 country_code = "at",
                                                region_code = "AT111",
                                                climate_experiment = "RCP8.5",
                                                pathway_description="with_behavioural_changes",
                                                result_format = "df"
                                                )

http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?region=AT111&pathway=with_behavioural_changes&climate_experiment=RCP8.5
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=2&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=3&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=4&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=5&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=6&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=7&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=8&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=9&pathway=with_behavioural_changes&region=AT111
http://data.localised-project.eu/dsp/v6/at/region_data/mini_version/?climate_experiment=RCP8.5&page=10&pathway=with_behavioural_changes&region=AT111

INFO:utils:Elapsed time for <function get_region_data at 0x000002958E211260>: 0.95 minutes

In [15]:
region_data_minimal_set[region_data_minimal_set["var_name"] == "cimp_ts_heatwaves_intensity_maximum"]

,value,year,pathway,climate_experiment,var_name,var_unit,taggings
169,6.712500,2025.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."
170,6.440000,2030.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."
171,7.691667,2035.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."
174,8.467742,2040.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."
176,10.008065,2045.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."
178,10.588710,2050.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."
179,15.072581,2075.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."
180,26.298387,2100.0,None,RCP8.5,cimp_ts_heatwaves_intensity_maximum,number,"[{'tag_dimension': 'sector', 'tag_name': 'clim..."