### Example script - shows how to use this API client to access a single variable data for all regions at a specified resolution, in a specified country.

#### Load required libraries

In [1]:
from zoomin_client import client

#### Get metadata

In [2]:
var_metadata = client.get_variable_metadata(version="v6", 
                                            country_code="de",
                                            result_format="df"
                                )

#NOTE: to filter on a particular variable, use "variable" parameter

http://data.localised-project.eu/dsp/v6/de/variable_metadata/
http://data.localised-project.eu/dsp/v6/de/variable_metadata/?page=2

In [3]:
var_metadata

,var_name,var_description,var_unit,data_last_update,var_aggregation_method,taggings,post_disagg_calculation_eq,var_source_name,var_source_link,var_source_citation,var_source_license,original_resolution
0,active_citizenship,Share of people who claimed they had participa...,percentage,2020,AVG,"[{'tag_dimension': 'sector', 'tag_name': 'gene...",None,EU Social Progress Index - 2020,https://cohesiondata.ec.europa.eu/stories/s/EU...,"Paola Annoni and Paolo Bolsi, “EU Social Progr...",Creative Commons Attribution 4.0 International...,NUTS0
1,agriculture_with_natural_vegetation_cover,Please note that only elements which are at le...,square kilometer,2018,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'land...",None,Copernicus Land Monitoring Service - Corine La...,https://land.copernicus.eu/pan-european/corine...,"Corine Land Cover, ‘CLC 2018 — Copernicus Land...",None,LAU
2,agro_forestry_areas_cover,Please note that only elements which are at le...,square kilometer,2018,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'land...",None,Copernicus Land Monitoring Service - Corine La...,https://land.copernicus.eu/pan-european/corine...,"Corine Land Cover, ‘CLC 2018 — Copernicus Land...",None,LAU
3,air_transport_of_freight,Traffic and transport measurement: Freight loa...,Mt,2025-05-20,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'tran...",None,Eurostat,https://ec.europa.eu/eurostat/databrowser/view...,"Eurostat, ‘Air transport of freight by NUTS 2 ...",Creative Commons Attribution 4.0 International...,NUTS2
4,air_transport_of_passengers,Traffic and transport measurement: Passengers ...,number,2025-05-20,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'tran...",None,Eurostat,https://ec.europa.eu/eurostat/databrowser/view...,"Eurostat, ‘Air transport of passengers by NUTS...",Creative Commons Attribution 4.0 International...,NUTS2
...,...,...,...,...,...,...,...,...,...,...,...,...
860,eucalc_str_subdaily_flywheel,None,percentage,2022,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'ener...",None,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0
861,eucalc_str_subdaily_natural_gas_prod,None,percentage,2022,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'ener...",None,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0
862,eucalc_str_weekly_phs,None,percentage,2022,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'ener...",None,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0
863,eucalc_str_weekly_ptx,None,percentage,2022,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'ener...",None,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0
864,eucalc_str_weekly_natural_gas_prod,None,percentage,2022,SUM,"[{'tag_dimension': 'sector', 'tag_name': 'ener...",None,LOCALISED Deliverable 2.3,https://www.localised-project.eu/wp-content/up...,"Costa L., (2023), Library of model outputs at ...",Creative Commons Attribution-NonCommercial-Sha...,NUTS0

#### Get proxy details

In [4]:
proxy_details = client.get_proxy_details(version="v6", 
                                         country_code="de",
                                            variable="eucalc_agr_emissions_co2e_liv_enteric_meat_poultry"
                                )

In [5]:
proxy_details

[{'year': 2020,
  'disaggregation_binary_criteria': None,
  'disaggregation_proxy': 'number_of_chickens',
  'proxy_confidence_level': 4},
 {'year': 2025,
  'disaggregation_binary_criteria': None,
  'disaggregation_proxy': 'number_of_chickens',
  'proxy_confidence_level': 4},
 {'year': 2030,
  'disaggregation_binary_criteria': None,
  'disaggregation_proxy': 'number_of_chickens',
  'proxy_confidence_level': 4},
 {'year': 2035,
  'disaggregation_binary_criteria': None,
  'disaggregation_proxy': 'number_of_chickens',
  'proxy_confidence_level': 4},
 {'year': 2040,
  'disaggregation_binary_criteria': None,
  'disaggregation_proxy': 'number_of_chickens',
  'proxy_confidence_level': 4},
 {'year': 2045,
  'disaggregation_binary_criteria': None,
  'disaggregation_proxy': 'number_of_chickens',
  'proxy_confidence_level': 4},
 {'year': 2050,
  'disaggregation_binary_criteria': None,
  'disaggregation_proxy': 'number_of_chickens',
  'proxy_confidence_level': 4}]

#### Get data

In [6]:
result_data = client.get_variable_data(version="v6", 
                                    country_code="de",
                                variable="eucalc_agr_emissions_n2o_liv_applied_meat_poultry",
                                spatial_resolution="NUTS3",
                                result_format="df",
                                      )

http://data.localised-project.eu/dsp/v6/de/variable_data/?resolution=NUTS3&variable=eucalc_agr_emissions_n2o_liv_applied_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=2&resolution=NUTS3&variable=eucalc_agr_emissions_n2o_liv_applied_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=3&resolution=NUTS3&variable=eucalc_agr_emissions_n2o_liv_applied_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=4&resolution=NUTS3&variable=eucalc_agr_emissions_n2o_liv_applied_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=5&resolution=NUTS3&variable=eucalc_agr_emissions_n2o_liv_applied_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=6&resolution=NUTS3&variable=eucalc_agr_emissions_n2o_liv_applied_meat_poultry

INFO:utils:Elapsed time for <function get_variable_data at 0x0000028E069AAB60>: 0.09 minutes

In [7]:
result_data

,value,year,pathway,climate_experiment,region_code,value_confidence_level
0,1.731873e-06,2025,national,None,DE933,MEDIUM
1,3.701591e-06,2025,national,None,DE934,MEDIUM
2,3.082310e-06,2025,national,None,DE935,MEDIUM
3,1.709409e-06,2025,national,None,DEA5A,MEDIUM
4,3.368166e-06,2025,national,None,DEA5B,MEDIUM
...,...,...,...,...,...,...
609,4.554473e-06,2030,national,None,DEE0C,MEDIUM
610,1.268881e-06,2030,national,None,DEG06,MEDIUM
611,8.252050e-07,2030,national,None,DEG07,MEDIUM
612,1.701033e-06,2030,national,None,DEG0P,MEDIUM
613,7.931022e-07,2030,national,None,DE402,MEDIUM

In [8]:
result_data[result_data["region_code"].str.startswith("DEA23")]

,value,year,pathway,climate_experiment,region_code,value_confidence_level
278,2.387271e-07,2025,national,None,DEA23,MEDIUM
679,2.600738e-07,2020,with_behavioural_changes,None,DEA23,MEDIUM
80,1.981684e-07,2025,with_behavioural_changes,None,DEA23,MEDIUM
481,1.629464e-07,2030,with_behavioural_changes,None,DEA23,MEDIUM
882,2.148900e-07,2035,national,None,DEA23,MEDIUM
283,2.056397e-07,2040,national,None,DEA23,MEDIUM
684,1.072671e-07,2040,with_behavioural_changes,None,DEA23,MEDIUM
85,1.908749e-07,2045,national,None,DEA23,MEDIUM
486,1.750428e-07,2050,national,None,DEA23,MEDIUM
887,1.355515e-07,2035,with_behavioural_changes,None,DEA23,MEDIUM
288,4.696271e-08,2050,with_behavioural_changes,None,DEA23,MEDIUM
689,7.667018e-08,2045,with_behavioural_changes,None,DEA23,MEDIUM
90,2.607853e-07,2020,national,None,DEA23,MEDIUM
491,2.230729e-07,2030,national,None,DEA23,MEDIUM

In [9]:
result_data = client.get_variable_data(version="v6", 
                               country_code="de",
                                variable="eucalc_agr_emissions_co2e_liv_enteric_meat_poultry",
                                spatial_resolution="NUTS3",
                                result_format="df",
                                      )

http://data.localised-project.eu/dsp/v6/de/variable_data/?resolution=NUTS3&variable=eucalc_agr_emissions_co2e_liv_enteric_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=2&resolution=NUTS3&variable=eucalc_agr_emissions_co2e_liv_enteric_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=3&resolution=NUTS3&variable=eucalc_agr_emissions_co2e_liv_enteric_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=4&resolution=NUTS3&variable=eucalc_agr_emissions_co2e_liv_enteric_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=5&resolution=NUTS3&variable=eucalc_agr_emissions_co2e_liv_enteric_meat_poultry
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=6&resolution=NUTS3&variable=eucalc_agr_emissions_co2e_liv_enteric_meat_poultry

INFO:utils:Elapsed time for <function get_variable_data at 0x0000028E069AAB60>: 0.06 minutes

In [10]:
result_data_proxy = client.get_variable_data(version="v6", 
                                             country_code="de",
                                variable="number_of_poultry",
                                spatial_resolution="NUTS3",
                                result_format="df",
                                      )

INFO:utils:Elapsed time for <function get_variable_data at 0x0000028E069AAB60>: 0.0 minutes

http://data.localised-project.eu/dsp/v6/de/variable_data/?resolution=NUTS3&variable=number_of_poultry

#### Get EUCalc data - filtered on a single pathway

In [11]:
result_data = client.get_variable_data(version="v6", 
                                       country_code="de",
                                variable="eucalc_agr_co2e_liv_treated_meat_oth_animals_ei",
                                pathway_description="national",
                                spatial_resolution="NUTS3",
                                result_format="df",
                                      )

http://data.localised-project.eu/dsp/v6/de/variable_data/?resolution=NUTS3&variable=eucalc_agr_co2e_liv_treated_meat_oth_animals_ei&pathway=national
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=2&pathway=national&resolution=NUTS3&variable=eucalc_agr_co2e_liv_treated_meat_oth_animals_ei
http://data.localised-project.eu/dsp/v6/de/variable_data/?page=3&pathway=national&resolution=NUTS3&variable=eucalc_agr_co2e_liv_treated_meat_oth_animals_ei

INFO:utils:Elapsed time for <function get_variable_data at 0x0000028E069AAB60>: 0.05 minutes

In [12]:
result_data

,value,year,pathway,climate_experiment,region_code,value_confidence_level
0,1.518366e-06,2020,national,None,DE933,MEDIUM
1,7.875814e-06,2020,national,None,DE934,MEDIUM
2,1.341554e-06,2020,national,None,DE935,MEDIUM
3,3.209693e-06,2020,national,None,DEA5A,MEDIUM
4,3.102903e-06,2020,national,None,DEA5B,MEDIUM
...,...,...,...,...,...,...
802,9.368532e-06,2050,national,None,DEE0C,MEDIUM
803,8.250562e-06,2050,national,None,DEG06,MEDIUM
804,8.166108e-06,2050,national,None,DEG07,MEDIUM
805,3.164036e-06,2050,national,None,DEG0P,MEDIUM
806,5.073815e-07,2050,national,None,DE402,MEDIUM

#### Get climate data - filtered on a single climate experiment

In [13]:
result_data = client.get_variable_data(version="v6", 
                                       country_code="de",
                                variable="cproj_annual_maximum_temperature_cooling_degree_days",
                                climate_experiment="RCP2.6",
                                spatial_resolution="NUTS3",
                                result_format="df",
                                      )

http://data.localised-project.eu/dsp/v6/de/variable_data/?resolution=NUTS3&variable=cproj_annual_maximum_temperature_cooling_degree_days&climate_experiment=RCP2.6
http://data.localised-project.eu/dsp/v6/de/variable_data/?climate_experiment=RCP2.6&page=2&resolution=NUTS3&variable=cproj_annual_maximum_temperature_cooling_degree_days
http://data.localised-project.eu/dsp/v6/de/variable_data/?climate_experiment=RCP2.6&page=3&resolution=NUTS3&variable=cproj_annual_maximum_temperature_cooling_degree_days
http://data.localised-project.eu/dsp/v6/de/variable_data/?climate_experiment=RCP2.6&page=4&resolution=NUTS3&variable=cproj_annual_maximum_temperature_cooling_degree_days

INFO:utils:Elapsed time for <function get_variable_data at 0x0000028E069AAB60>: 0.11 minutes